#include <stdio.h>

int main(int argc, char **argv)
{
    FILE *in, *out, *chunk;
    unsigned int chunks[8],magic,chunksize,w,x,y,z,gpr;
    unsigned short gpr2,gpr3,indices=0;
    unsigned char width[256],counter=0;
    char chunkname[11];
    in=fopen(argv[1],"rb");
    magic=(unsigned int)((fgetc(in)<<24)|(fgetc(in)<<16)|(fgetc(in)<<8)|fgetc(in));
    if(magic==0x5A534909)
    {
        out=fopen("temp.cmb","wb");
        while(magic!=0x636D6220)
        {
            magic=(unsigned int)((fgetc(in)<<24)|(fgetc(in)<<16)|(fgetc(in)<<8)|fgetc(in));
        }
        chunksize=(unsigned int)(fgetc(in)|(fgetc(in)<<8)|(fgetc(in)<<16)|(fgetc(in)<<24));
        fseek(in,-8,SEEK_CUR);
        for(x=0;x<chunksize;x+=1){fputc(fgetc(in),out);}
        fclose(out);
        fclose(in);
        in=fopen("temp.cmb","rb");
    }
    out=fopen(argv[2],"wb");
    fseek(in,0x24,SEEK_SET);
    for(x=0;x<8;x+=1)
    {
        if(x==1){fseek(in,4,SEEK_CUR);}
        chunks[x]=(unsigned int)(fgetc(in)|(fgetc(in)<<8)|(fgetc(in)<<16)|(fgetc(in)<<24));
    }
    for(x=0;x<8;x+=1)
    {
        sprintf(chunkname,"chunk%d.bin",x);
        chunk=fopen(chunkname,"wb");
        fseek(in,chunks[x]+4,SEEK_SET);
        chunksize=(unsigned int)(fgetc(in)|(fgetc(in)<<8)|(fgetc(in)<<16)|(fgetc(in)<<24));
        if(x==1){chunksize=chunks[2]-chunks[1];}
        if(x==6){chunksize=chunks[7]-chunks[6];}
        if(x==7)
        {
            fseek(in,0,SEEK_END);
            chunksize=ftell(in)-chunks[7];
        }
        fseek(in,chunks[x],SEEK_SET);
        for(y=0;y<chunksize;y+=1){fputc(fgetc(in),chunk);}
        fclose(chunk);
    }
    fseek(in,0x10,SEEK_SET);
    fputc(0x63,out);fputc(0x6D,out);fputc(0x62,out);fputc(0x20,out);
    fputc(0,out);fputc(0,out);fputc(0,out);fputc(0,out);
    fputc(6,out);fputc(0,out);fputc(0,out);fputc(0,out);
    fputc(0,out);fputc(0,out);fputc(0,out);fputc(0,out);
    for(x=0;x<0x34;x+=1)
    {
        if(x<0x10){fputc(fgetc(in),out);}
        else{fputc(0,out);}
    }
    fclose(in);
    for(x=0;x<8;x+=1)
    {
        chunks[x]=ftell(out);
        if(x==0)
        {
            chunk=fopen("chunk0.bin","rb");
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fseek(chunk,4,SEEK_CUR);
            gpr=(unsigned int)(fgetc(chunk)|(fgetc(chunk)<<8)|(fgetc(chunk)<<16)|(fgetc(chunk)<<24));
            chunksize=0x10+0x28*gpr;
            fputc(chunksize&0xFF,out);
            fputc((chunksize>>8)&0xFF,out);
            fputc((chunksize>>16)&0xFF,out);
            fputc((chunksize>>24)&0xFF,out);
            fputc(gpr&0xFF,out);
            fputc((gpr>>8)&0xFF,out);
            fputc((gpr>>16)&0xFF,out);
            fputc((gpr>>24)&0xFF,out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            for(y=0;y<gpr;y+=1)
            {
                fputc(fgetc(chunk),out);
                fputc(0,out);
                fseek(chunk,1,SEEK_CUR);
                for(z=0;z<0x26;z+=1)
                {
                    fputc(fgetc(chunk),out);
                }
                fseek(chunk,4,SEEK_CUR);
            }
        }
        if(x==1)
        {
            chunk=fopen("chunk1.bin","rb");
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            gpr=(unsigned int)(fgetc(chunk)|(fgetc(chunk)<<8)|(fgetc(chunk)<<16)|(fgetc(chunk)<<24));
            fputc(gpr&0xFF,out);
            fputc((gpr>>8)&0xFF,out);
            fputc((gpr>>16)&0xFF,out);
            fputc((gpr>>24)&0xFF,out);
            for(y=0;y<gpr;y+=1)
            {
                for(z=0;z<0x15C;z+=1)
                {
                    fputc(fgetc(chunk),out);
                }
                fseek(chunk,0x10,SEEK_CUR);
            }
            gpr=ftell(chunk);
            fseek(chunk,0,SEEK_END);
            chunksize=ftell(chunk);
            fseek(chunk,gpr,SEEK_SET);
            for(y=gpr;y<chunksize;y+=1)
            {
                fputc(fgetc(chunk),out);
            }
            
        }
        if(x==2)
        {
            chunk=fopen("chunk2.bin","rb");
            fseek(chunk,4,SEEK_CUR);
            chunksize=(unsigned int)(fgetc(chunk)|(fgetc(chunk)<<8)|(fgetc(chunk)<<16)|(fgetc(chunk)<<24));
            fseek(chunk,-8,SEEK_CUR);
            for(y=0;y<chunksize;y+=1){fputc(fgetc(chunk),out);}
        }
        if(x==3)
        {
            chunk=fopen("chunk3.bin","rb");
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fseek(chunk,0x14,SEEK_CUR);
            gpr=(unsigned int)(fgetc(chunk)|(fgetc(chunk)<<8)|(fgetc(chunk)<<16)|(fgetc(chunk)<<24));
            fseek(chunk,-0x18,SEEK_CUR);
            chunksize=(unsigned int)(fgetc(chunk)|(fgetc(chunk)<<8)|(fgetc(chunk)<<16)|(fgetc(chunk)<<24))-0x24*gpr;
            fputc(chunksize&0xFF,out);
            fputc((chunksize>>8)&0xFF,out);
            fputc((chunksize>>16)&0xFF,out);
            fputc((chunksize>>24)&0xFF,out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            chunksize=(unsigned int)(fgetc(chunk)|(fgetc(chunk)<<8)|(fgetc(chunk)<<16)|(fgetc(chunk)<<24))-8*gpr;
            fputc(chunksize&0xFF,out);
            fputc((chunksize>>8)&0xFF,out);
            fputc((chunksize>>16)&0xFF,out);
            fputc((chunksize>>24)&0xFF,out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fseek(chunk,4,SEEK_CUR);
            fputc(gpr&0xFF,out);
            fputc((gpr>>8)&0xFF,out);
            fputc((gpr>>16)&0xFF,out);
            fputc((gpr>>24)&0xFF,out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            for(y=0;y<gpr;y+=1)
            {
                fputc(fgetc(chunk),out);
                fputc(fgetc(chunk),out);
                fputc(fgetc(chunk),out);
                fputc(fgetc(chunk),out);
                fseek(chunk,8,SEEK_CUR);
            }
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            chunksize=(unsigned int)(fgetc(chunk)|(fgetc(chunk)<<8)|(fgetc(chunk)<<16)|(fgetc(chunk)<<24))-0x1C*gpr;
            fputc(chunksize&0xFF,out);
            fputc((chunksize>>8)&0xFF,out);
            fputc((chunksize>>16)&0xFF,out);
            fputc((chunksize>>24)&0xFF,out);
            fseek(chunk,4,SEEK_CUR);
            fputc(gpr&0xFF,out);
            fputc((gpr>>8)&0xFF,out);
            fputc((gpr>>16)&0xFF,out);
            fputc((gpr>>24)&0xFF,out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            for(y=0;y<gpr;y+=1)
            {
                gpr2=(unsigned short)(fgetc(chunk)|(fgetc(chunk)<<8))-0x1C*y;
                fputc(gpr2&0xFF,out);
                fputc((gpr2>>8)&0xFF,out);
            }
            while(ftell(chunk)&3){fseek(chunk,1,SEEK_CUR);}
            while(ftell(out)&3){fputc(0,out);}
            for(y=0;y<gpr;y+=1)
            {
                fputc(fgetc(chunk),out);
                fputc(fgetc(chunk),out);
                fputc(fgetc(chunk),out);
                fputc(fgetc(chunk),out);
                chunksize=(unsigned int)(fgetc(chunk)|(fgetc(chunk)<<8)|(fgetc(chunk)<<16)|(fgetc(chunk)<<24))-0x1C;
                fputc(chunksize&0xFF,out);
                fputc((chunksize>>8)&0xFF,out);
                fputc((chunksize>>16)&0xFF,out);
                fputc((chunksize>>24)&0xFF,out);
                gpr2=(unsigned short)(fgetc(chunk)|(fgetc(chunk)<<8));
                fputc(gpr2&0xFF,out);
                fputc((gpr2>>8)&0xFF,out);
                for(z=0;z<0xFE;z+=1)
                {
                    if(z==0x52){fseek(chunk,0x1C,SEEK_CUR);}
                    fputc(fgetc(chunk),out);
                }
                for(z=0;z<gpr2;z+=1)
                {
                    gpr3=(unsigned short)(fgetc(chunk)|(fgetc(chunk)<<8))-0x1C;
                    fputc(gpr3&0xFF,out);
                    fputc((gpr3>>8)&0xFF,out);
                }
                while(ftell(chunk)&3){fseek(chunk,1,SEEK_CUR);}
                while(ftell(out)&3){fputc(0,out);}
                for(z=0;z<gpr2;z+=1)
                {
                    fputc(fgetc(chunk),out);
                    fputc(fgetc(chunk),out);
                    fputc(fgetc(chunk),out);
                    fputc(fgetc(chunk),out);
                    chunksize=(unsigned int)(fgetc(chunk)|(fgetc(chunk)<<8)|(fgetc(chunk)<<16)|(fgetc(chunk)<<24));
                    fputc(chunksize&0xFF,out);
                    fputc((chunksize>>8)&0xFF,out);
                    fputc((chunksize>>16)&0xFF,out);
                    fputc((chunksize>>24)&0xFF,out);
                    for(w=8;w<chunksize-8;w+=1){fputc(fgetc(chunk),out);}
                    width[counter]=fgetc(chunk);
                    counter+=1;
                    fputc(3,out);
                    fputc(fgetc(chunk),out);
                    fputc(fgetc(chunk),out);
                    fputc(fgetc(chunk),out);
                    gpr3=(unsigned short)(fgetc(chunk)|(fgetc(chunk)<<8));
                    fputc(gpr3&0xFF,out);
                    fputc((gpr3>>8)&0xFF,out);
                    fseek(chunk,2,SEEK_CUR);
                    fputc(indices&0xFF,out);
                    fputc((indices>>8)&0xFF,out);
                    indices+=gpr3;
                }
            }
        }
        if(x==4)
        {
            chunk=fopen("chunk4.bin","rb");
            fseek(chunk,4,SEEK_CUR);
            chunksize=(unsigned int)(fgetc(chunk)|(fgetc(chunk)<<8)|(fgetc(chunk)<<16)|(fgetc(chunk)<<24));
            fseek(chunk,-8,SEEK_CUR);
            for(y=0;y<chunksize;y+=1){fputc(fgetc(chunk),out);}
        }
        if(x==5)
        {
            chunk=fopen("chunk5.bin","rb");
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            chunksize=(unsigned int)(fgetc(chunk)|(fgetc(chunk)<<8)|(fgetc(chunk)<<16)|(fgetc(chunk)<<24))-8;
            fputc(chunksize&0xFF,out);
            fputc((chunksize>>8)&0xFF,out);
            fputc((chunksize>>16)&0xFF,out);
            fputc((chunksize>>24)&0xFF,out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            fputc(fgetc(chunk),out);
            for(y=0;y<8;y+=1)
            {
                if(y==2){fseek(chunk,8,SEEK_CUR);}
                fputc(fgetc(chunk),out);
                fputc(fgetc(chunk),out);
                fputc(fgetc(chunk),out);
                fputc(fgetc(chunk),out);
                chunksize=(unsigned int)(fgetc(chunk)|(fgetc(chunk)<<8)|(fgetc(chunk)<<16)|(fgetc(chunk)<<24))-8;
                fputc(chunksize&0xFF,out);
                fputc((chunksize>>8)&0xFF,out);
                fputc((chunksize>>16)&0xFF,out);
                fputc((chunksize>>24)&0xFF,out);
            }
            gpr=ftell(chunk);
            fseek(chunk,0,SEEK_END);
            chunksize=ftell(chunk);
            fseek(chunk,gpr,SEEK_SET);
            for(y=gpr;y<chunksize;y+=1){fputc(fgetc(chunk),out);}
        }
        if(x==6)
        {
            fclose(out);
            out=fopen(argv[2],"rb+");
            chunk=fopen("chunk6.bin","rb");
            fseek(out,chunks[3],SEEK_SET);
            for(y=0;y<counter;y+=1)
            {
                while(magic!=0x70726D20)
                {
                    magic=(unsigned int)((fgetc(out)<<24)|(fgetc(out)<<16)|(fgetc(out)<<8)|fgetc(out));
                }
                magic=0;
                fseek(out,0x10,SEEK_CUR);
                gpr2=(unsigned short)(fgetc(out)|(fgetc(out)<<8));
                fseek(out,2,SEEK_CUR);
                gpr=ftell(out);
                fseek(out,0,SEEK_END);
                for(z=0;z<gpr2;z+=1)
                {
                    if(width[y]==1)
                    {
                        fputc(fgetc(chunk),out);
                        fputc(0,out);
                    }
                    else if(width[y]==3)
                    {
                        fputc(fgetc(chunk),out);
                        fputc(fgetc(chunk),out);
                    }
                }
                fseek(out,gpr,SEEK_SET);
                while(ftell(chunk)&1){fseek(chunk,1,SEEK_CUR);}
            }
            fseek(out,0,SEEK_END);
            while(ftell(out)&0xF){fputc(0,out);}
        }
        if(x==7)
        {
            chunk=fopen("chunk7.bin","rb");
            fseek(chunk,0,SEEK_END);
            chunksize=ftell(chunk);
            fseek(chunk,0,SEEK_SET);
            for(y=0;y<chunksize;y+=1){fputc(fgetc(chunk),out);}
        }
        fclose(chunk);
    }
    chunksize=ftell(out);
    fseek(out,4,SEEK_SET);
    fputc(chunksize&0xFF,out);
    fputc((chunksize>>8)&0xFF,out);
    fputc((chunksize>>16)&0xFF,out);
    fputc((chunksize>>24)&0xFF,out);
    fseek(out,0x20,SEEK_SET);
    fputc(indices&0xFF,out);
    fputc((indices>>8)&0xFF,out);
    fseek(out,2,SEEK_CUR);
    for(x=0;x<8;x+=1)
    {
        fputc(chunks[x]&0xFF,out);
        fputc((chunks[x]>>8)&0xFF,out);
        fputc((chunks[x]>>16)&0xFF,out);
        fputc((chunks[x]>>24)&0xFF,out);
    }
    return 0;
}
